apiVersion: v2
name: kafkaecosystem
version: 1.1.0
appVersion: 1.11.12
description: This Chart deploys Kafka.
dependencies:
  - name: kafka
    condition: kafka.enabled
    repository: https://charts.bitnami.com/bitnami
    version: {{ "20.0.2" | ENV('VERSION') }}
